eureka:
  instance:
    hostname: localhost
  client:
    server-uri:
      defaultZone: http://localhost:8761/eureka

spring:
  jwt:
    secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    jwtExpirationInMs: 1800000 # 30 minute
  datasource:
    url: jdbc:postgresql://localhost:5432/meal-mate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true

  liquibase:
    change-log: db/changelog/liquibase-changelog.yaml
    enabled: true

  application:
    name: user-service
#  config:
#    import: optional:configserver:http://localhost:8888
server:
  port: 8001
