server:
  port: 8222

eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: hotel-service
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/menu/**,/api/v1/hotel/**
            filters:
              - name: CircuitBreaker
                args:
                  name: fallBack
                  fallbackUri: forward:/fall-back
              - name: JWTAuthenticationFilter
              - name: PreFilter
              - name: PostFilter

          - id: order-service
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/order/**
            filters:
              - name: CircuitBreaker
                args:
                  name: fallBack
                  fallbackUri: forward:/fall-back
              - name: JWTAuthenticationFilter
              - name: PreFilter


          - id: user-service
            uri: http://localhost:8001
            predicates:
              - Path=/auth/**,/api/v1/user/**
            filters:
              - name: JWTAuthenticationFilter
              - name: CircuitBreaker
                args:
                  name: fallBack
                  fallbackUri: forward:/fall-back


  jwt:
    secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    jwtExpirationInMs: 1800000 # 30 minute
