server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:\configurations

# we can config this in git also server.git,uri,search-paths:

#management:
#  endpoint:
#    web:
#      exposure:
#        include: "*"
#      expose: "*"



